### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by billyprice1** [exula/Proxmox-Dashboard#1]
Hi i Dont know how to set this up you got an install guide

**Comment by exula** [comment]
You are the first person to ask for one!
I'll work on one and let you know.

**Comment by billyprice1** [comment]
Ok thanks for the fast reply This seems a good project if you want a private gitlab just ask

**Comment by billyprice1** [comment]
Is this a problam   Problem 1
    - Installation request for zzantares/proxmoxve v3.0.0 -> satisfiable by zzantares/proxmoxve[v3.0.0].
    - zzantares/proxmoxve v3.0.0 requires lib-curl * -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - zzantares/proxmoxve v3.0.0 requires lib-curl * -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - h1g/proxmox v1.0.0 requires zzantares/proxmoxve ~3.0 -> satisfiable by zzantares/proxmoxve[v3.0.0].
    - Installation request for h1g/proxmox v1.0.0 -> satisfiable by h1g/proxmox[v1.0.0].

**Comment by exula** [comment]
You need to have **libcurl** installed on your system. 

`sudo apt install libcurl3` should do the trick if you are Ubuntu or Debian based system

**Comment by billyprice1** [comment]
That is installed libcurl3 http error 500 :( still

**Comment by exula** [comment]
I just updated the README with an installation section. The biggest thing I think you are running into is copying the .env.example file to .env and tweaking the settings.

**Comment by billyprice1** [comment]
I done that but composer install is not working and thanks

**Comment by exula** [comment]
It's still asking for lib-curl, what OS are on you?

**Comment by billyprice1** [comment]
https://www.turnkeylinux.org/laravel

**Comment by exula** [comment]
Does ```php -m | grep curl``` show that curl is installed?
If not can you run ```apt-get install php-curl```

Thanks for being a guinea pig, i've never had anyone else try to install this.

**Comment by billyprice1** [comment]
I done apt-get install php-curl it installing it partly now also you looking for some help or something like a  colab or something im thinking about whmcs support or billing in the future

**Comment by exula** [comment]
The main reason I wrote this was the balancing of QEMU vm's across nodes, anything other features are out of our scope and not something we need.

At my work we are building out a blade system and we want to spread the load of VM's across all the nodes. We are currently at a cluster of 4 nodes. This does a good job of migrating VM's across all the PVE nodes.

**Comment by billyprice1** [comment]
php artisan serve --host 0.0.0.0 Works but nothing on port 8080

**Comment by exula** [comment]
I think artisan serve goes out port 8000 not 8080, also you may have a firewall issue.

but if you are using turnkey that probably has Apache or NGINX already setup and looking to serve out at /var/www/laravel/ right? 

I've never used that turnkey install.

**Comment by billyprice1** [comment]
I worked that out also it works the first page but provision AuthenticationException in Proxmox.php line 217:
Can not login using credentials: [Host: 10.0.0.2:8006], [Username: @pam], [Password: na].

**Comment by exula** [comment]
Progress!!!!! It tried to talk to your proxmox node and did like your username.

In your .env file you have **PROXMOX_USER=<your username>** right?

**Comment by billyprice1** [comment]
https://pastebin.ubuntu.com/23645728/

**Comment by billyprice1** [comment]
Got fqdn removed that

**Comment by billyprice1** [comment]
Its working

**Comment by billyprice1** [comment]
Wait spoke to soon target storage dont work

**Comment by exula** [comment]
Log / Screenshot?

**Comment by billyprice1** [comment]
Its that you cant select the target storage box

**Comment by exula** [comment]
You don't have any storage other than the local disks for your Proxmox node huh? 
Yeah, I ignored 'local' because our installs all have shared storage. 

I'm working on a fix now.

**Comment by billyprice1** [comment]
No i dont mean that my hdds are hdd_1 hdd_2 hdd_3 but thay dont show up

**Comment by exula** [comment]
Pull down the latest code. there was a switched needle and haystack in app/Node.php

**Comment by exula** [comment]
This also assumes that you have some templates available to deploy. I should write that in the docs too.

**Comment by billyprice1** [comment]
Ok I will try it tommorow i will help you we could use readthedocs or something  do you mind me helping out

**Comment by exula** [comment]
I welcome the help! Currently this is a pet project of mine, the more the merrier. I'm just trying to fill the gap in some of the features that are missing from Proxmox as of right now.

**Comment by billyprice1** [comment]
Ye that what im trying to do proxmox is a good hypervisor but it lack some things such as 

Built In Billing
Email Notifcation
build it Status page 
I know this is achiveable with whmcs but dont like as im a web dev but i like billing panels and node management

**Comment by exula** [comment]
Closing old issue.
