### ISSUE TITLE
Error after setup

### ISSUE THREAD

**Issue by YYakovliev** [exula/Proxmox-Dashboard#3]
FatalErrorException in C:\Users\Neura\Desktop\Proxmox-Dashboard-master\vendor\guzzlehttp\guzzle\src\Event\Emitter.php line 49:
Cannot use lexical variable $eventName as a parameter name

**Comment by billyprice1** [comment]
try not to run it on windows?

**Comment by NeuraFTW** [comment]
> try not to run it on windows?

I have it on Homestead.

**Comment by exula** [comment]
I saw that once before, and it was an incompatibility with a bunch of packages.
I also just noticed that this repo isn't up to date with the latest version of what I have at running at our work instance. 

I'm going to work on getting this updated with the lastest version that I have working today. Keep an eye out and I bet this problem will go away.

**Comment by exula** [comment]
Go ahead and pull down a new clone of the repo, composer install, npm install and see if it works any better.

**Comment by exula** [comment]
@YYakovliev I haven't heard back from you so I'm closing this issue.
