### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MG-100** [exula/Proxmox-Dashboard#4]
When i go to the site i become this error:
"Unable to parse URI: https://:8006/api2/json/access/ticket"

**Comment by mrbrazzi** [comment]
You have to set the environment variable `PROXMOX_HOST` in `.env` file with the IP or FQDN of your Proxmox server.

**Comment by exula** [comment]
Yes, what @mrbrazzi said is 100% correct.

**Comment by seiyukaras** [comment]
You must also put the user and password variables, but making these changes gave this error
InvalidArgumentException
Unable to parse URI: https://:8006/api2/json/access/ticket
