### ISSUE TITLE
PVE7 not working ?

### ISSUE THREAD

**Issue by tonywtrd** [exula/Proxmox-Dashboard#63]
Hello,

First of all, thank for sharing this.

I've been struggling finding the right user or even group permission for been able to use it perfectly.

For a pool setup, with bunch of VM, what and the user having "administrator" permission to this pools, it show me no vm, while there some for this user.

I also tried givind permission with path "/ -> adminstrator" to this user and i was not able to see vm nor deploi.

What is the right set up for the permission for a PAM real user as i tried a bunch and alway had something not working while using other permission, the one not wroked before came to work but some other like viewing vm was giving page error.

Do im missing something ?

Actually, the most frquent error i encountered was ".... no template ->vm" something like that (i will update as i am unable to connect on server  now.

Can you just tell me whag your current set up for permissions and user, and so on ? 

 I use PVE 7.1

Thanks alot

**Comment by exula** [comment]
We are currently running this against a PVE 6.4-8 environment, we haven't made the jump to PVE 7.1
There is a chance something changed in the API that I'm poking at with this.

It should mimic whatever permissions the user has in PVE, so I'm sure it's something erroring out and causing the AJAX calls to fail, which is why you wouldn't be able to see an VMS

Once you can get some logs from storage/laravel.log let me know and I see if It makes any sense!

**Comment by tonywtrd** [comment]
Hello, thanks for this fast answer.

Here the logs; 
(Actually, i remember tried it with an PVE6 environment and never had this error.)

Not sure if value name from parameter changed but i tried many thing and never been able to make it work;


#virtualmachines

**`Facade\Ignition\Exceptions\ViewException Undefined property: stdClass::$template (View: /root/prox/resources/views/virtualmachines.blade.php)
http://........:8000/virtualmachines`**


`
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
resources/views/virtualmachines.blade.php:11

...
...
11.          @if($vm->template != 1)
...
...`


Here the views of VM (single on i have now) from Laravel web inspector/error page:

`Illuminate\Database\Eloquent\Collection {#426
  #items: array:1 [
    0 => {#453
      +"netout": 0
      +"uptime": 0
      +"cpu": 0
      +"name": "Gfg"
      +"vmid": 102
      +"mem": 0
      +"maxmem": 2147483648
      +"maxdisk": 34359738368
      +"disk": 0
      +"diskwrite": 0
      +"netin": 0
      +"status": "stopped"
      +"diskread": 0
      +"cpus": 2
      +"config": {#457 …22}
    }
  ]
}
`

**Comment by tonywtrd** [comment]
By accessing API refs of PVE, 

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/template

```
You need 'VM.Allocate' permissions on /vms/{vmid}
Check: ["perm","/vms/{vmid}",["VM.Allocate"]]
```

![image](https://user-images.githubusercontent.com/86543533/147929240-31d816fa-2f51-4856-9567-00f1dee8480e.jpeg)

![image](https://user-images.githubusercontent.com/86543533/147929255-4d5b07eb-29de-43da-b57c-494929058756.jpeg)

**Comment by exula** [comment]
I'll see if I can get a PVE 7 host up and try to figure this out. 

I'm curious, does your PVE 7 have any Virtual Machine templates? If not can you try to make a dummy Virtual Machine and see if that works?

**Comment by exula** [comment]
Just wanted to let you know that I still haven't gotten a chance to stand up a test PVE7 machine.

**Comment by tonywtrd** [comment]
Hey Bradley,

Actually this look to be the way the app call PVE API, which are related to the PVE and their non-sense user permissions with over 80 "access path" 😬

,

**Comment by exula** [comment]
@tonywtrd can you pull down the latest code and try now? 

It looks like in the PVE7 they used to send the 'template' variable in the API if it was false or true, now they only send it if it's true? 
Seems silly.

This should be one step closer in getting you up and running.
